spring.application.name=api
jwts.security=${JWTS_SECURITY}
server.port=${PORT:8080}
# jwts.security=4Pm+VWXTf/9yC5Qw+zA3mee6CluFCUfVYM+41u2Me90=
# server.port=8080

eureka.client.service-url.defaultZone=http://service:8761/eureka
# eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true