spring.application.name=book
jwts.security=4Pm+VWXTf/9yC5Qw+zA3mee6CluFCUfVYM+41u2Me90=
server.port=8084

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/book
spring.datasource.username=postgres
spring.datasource.password=postgres30082004

spring.jpa.databs
