spring.application.name=book
# jwts.security=4Pm+VWXTf/9yC5Qw+zA3mee6CluFCUfVYM+41u2Me90=
# server.port=8084
jwts.security=${JWTS_SECURITY}
server.port=${PORT:8084}

spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.url=jdbc:postgresql://localhost:5432/book
# spring.datasource.username=postgres
# spring.datasource.password=postgres30082004
spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://service:8761/eureka
# eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
